### PR TITLE
using import-cost module instead of API

### PR DESCRIPTION
**Pull request by charlesbdudley**
The import cost API is no longer working so I decided to write this up.

Removed a bunch of dependencies and is much simpler now using the [import-cost](https://www.npmjs.com/package/import-cost) module. Note that they take care of caching on their end.

broadcastmessageandreviewcontainer_js_ ___documents_projects_1echo_1echo-web-front-end

### CODE REVIEW

**Comment by damdeez** [comment]
NIce! Excited to try this out

**Comment by reznord** [comment]
Amazing work 😍. Will check it out soon. 😄

**Comment by charlesbdudley** [comment]
Made a few improvements. With the way were were displaying markers before using `{ type: 'overlay' }` there was a visual bug where the overlays were rendered above tabs when scrolling.

I've also updated the colors to match the [Import Cost VSCode extension](https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost). If the size of the module is under 50k it is set to opacity 0.5, and if it is over 100k it is rendered as red.

broadcastmessageandreviewcontainer_js_ ___documents_projects_1echo_1echo-web-front-end

**Comment by siddharthkp** [comment]
Published!

An interesting thing is a simple update isn't enough. You have to go through this error. Hitting the rebuild button fixes it though.

screen shot 2017-10-14 at 12 49 09 am

**Comment by siddharthkp** [comment]
@charlesbdudley Can we also add the `Calculating...` message?

`import-cost` supports it:
```js
emitter.on('start', packages => /* mark those packages as "calculating..." */);
```

**Comment by charlesbdudley** [comment]
@siddharthkp thanks for the merge, and the comment in the readme! I'll have a PR for the calculating soon

**Comment by gregorym** [comment]
Dupe of #3 FYI :)

**Pull request merged**
