### PR TITLE
now showing "..." while calculating module size

### PR DESCRIPTION
**Pull request by charlesbdudley**

### CODE REVIEW

**Comment by charlesbdudley** [comment]
There's currently a flickering issue. Please wait to merge.

**Comment by charlesbdudley** [comment]
ok, good to go!

**Comment by siddharthkp** [comment]
Published in `1.2.0`

@charlesbdudley Added you as a collaborator on this repo, you can create branches here directly instead of a fork 😄

**Review by siddharthkp — COMMENTED** [review]
LGTM

**Pull request merged**
