### PR TITLE
Remove the outdated statement

### PR DESCRIPTION
**Pull request by SaraVieira**

### CODE REVIEW

**Comment by siddharthkp** [comment]
Not yet. Here's my anti-climated commit: https://github.com/siddharthkp/atom-import-cost/commit/30654bc5e79e4c0d550de46a2c0c36dc9e01e279

**Comment by reznord** [comment]
There's still time for this. Once my PR gets landed, we can do this 😄

**Comment by SaraVieira** [comment]
@siddharthkp Dang it ! Only saw the PR :(

**Comment by siddharthkp** [comment]
Fixed in https://github.com/siddharthkp/atom-import-cost/pull/11

**Pull request closed without merging**
